import { 
  LayoutDashboard, 
  Users, 
  BookOpen, 
  GraduationCap,
  CalendarDays,
  ClipboardCheck,
  Banknote,
  Library,
  MessageSquare,
  Bell,
  Settings,
  FileText,
  CreditCard,
} from "lucide-react";

export const menuData = {
  admin: [
    { icon: LayoutDashboard, label: "Dashboard", href: "/dashboard/admin" },
    { icon: Users, label: "Users", href: "/dashboard/admin/users" },
    { icon: BookOpen, label: "Classes", href: "/dashboard/admin/classes" },
    { icon: GraduationCap, label: "Subjects", href: "/dashboard/admin/subjects" },
    { icon: CalendarDays, label: "Timetable", href: "/dashboard/admin/timetable" },
    { icon: ClipboardCheck, label: "Exams", href: "/dashboard/admin/exams" },
    { icon: Banknote, label: "Finance", href: "/dashboard/admin/finance" },
    { icon: Library, label: "Library", href: "/dashboard/admin/library" },
    { icon: MessageSquare, label: "Messages", href: "/dashboard/admin/messages" },
    { icon: Bell, label: "Notices", href: "/dashboard/admin/notices" },
    { icon: Settings, label: "Settings", href: "/dashboard/admin/settings" },
  ],
  teacher: [
    { icon: LayoutDashboard, label: "Dashboard", href: "/dashboard/teacher" },
    { icon: BookOpen, label: "My Classes", href: "/dashboard/teacher/classes" },
    { icon: CalendarDays, label: "Timetable", href: "/dashboard/teacher/timetable" },
    { icon: ClipboardCheck, label: "Attendance", href: "/dashboard/teacher/attendance" },
    { icon: GraduationCap, label: "Grades", href: "/dashboard/teacher/grades" },
    { icon: FileText, label: "Assignments", href: "/dashboard/teacher/assignments" },
    { icon: MessageSquare, label: "Messages", href: "/dashboard/teacher/messages" },
    { icon: Bell, label: "Notices", href: "/dashboard/teacher/notices" },
  ],
  student: [
    { icon: LayoutDashboard, label: "Dashboard", href: "/dashboard/student" },
    { icon: CalendarDays, label: "Timetable", href: "/dashboard/student/timetable" },
    { icon: ClipboardCheck, label: "Attendance", href: "/dashboard/student/attendance" },
    { icon: GraduationCap, label: "Grades", href: "/dashboard/student/grades" },
    { icon: FileText, label: "Assignments", href: "/dashboard/student/assignments" },
    { icon: CreditCard, label: "Fees", href: "/dashboard/student/fees" },
    { icon: Library, label: "Library", href: "/dashboard/student/library" },
    { icon: MessageSquare, label: "Messages", href: "/dashboard/student/messages" },
  ],
  parent: [
    { icon: LayoutDashboard, label: "Dashboard", href: "/dashboard/parent" },
    { icon: ClipboardCheck, label: "Attendance", href: "/dashboard/parent/attendance" },
    { icon: GraduationCap, label: "Grades", href: "/dashboard/parent/grades" },
    { icon: CreditCard, label: "Fees", href: "/dashboard/parent/fees" },
    { icon: CalendarDays, label: "Events", href: "/dashboard/parent/events" },
    { icon: MessageSquare, label: "Messages", href: "/dashboard/parent/messages" },
    { icon: Bell, label: "Notices", href: "/dashboard/parent/notices" },
  ],
};