// ============================================================
// RBAC Seed — Roles, Permissions, Role-Permission Links
// Source of truth: docs/rbac.md (Section 6 — Role × Permission Matrix)
// ============================================================

import type { PrismaClient } from "@prisma/client";
import {
  ROLES,
  ROLE_METADATA,
  PERMISSIONS,
  PERMISSION_SEEDS,
  type RoleKey,
  type Permission,
} from "../../src/lib/permissions/constants";

// ------------------------------------------------------------
// Role → Permission mapping
// Exactly matches docs/rbac.md § 6
// ------------------------------------------------------------

const SYSTEM_ADMIN_PERMS: Permission[] = [
  // System
  PERMISSIONS.SYSTEM_READ,
  PERMISSIONS.SYSTEM_UPDATE,
  PERMISSIONS.SYSTEM_CONFIGURATION,
  PERMISSIONS.SYSTEM_MAINTENANCE,
  // Users
  PERMISSIONS.USERS_READ,
  PERMISSIONS.USERS_CREATE,
  PERMISSIONS.USERS_UPDATE,
  PERMISSIONS.USERS_ARCHIVE,
  PERMISSIONS.USERS_RESET_PASSWORD,
  PERMISSIONS.USERS_ASSIGN_ROLES,
  // Roles
  PERMISSIONS.ROLES_READ,
  PERMISSIONS.ROLES_CREATE,
  PERMISSIONS.ROLES_UPDATE,
  PERMISSIONS.ROLES_DELETE,
  // Permissions
  PERMISSIONS.PERMISSIONS_READ,
  PERMISSIONS.PERMISSIONS_ASSIGN,
  // Security
  PERMISSIONS.SECURITY_READ,
  PERMISSIONS.SECURITY_MANAGE,
  // Students (read only)
  PERMISSIONS.STUDENTS_READ,
  // Teachers (read only)
  PERMISSIONS.TEACHERS_READ,
  PERMISSIONS.TEACHER_ASSIGNMENTS_READ,
  // Academic structure (read only)
  PERMISSIONS.ACADEMIC_YEARS_READ,
  PERMISSIONS.TERMS_READ,
  PERMISSIONS.LEVELS_READ,
  PERMISSIONS.PATHWAYS_READ,
  PERMISSIONS.TRADES_READ,
  PERMISSIONS.SUBJECTS_READ,
  PERMISSIONS.MODULES_READ,
  PERMISSIONS.CLASSES_READ,
  PERMISSIONS.ENROLLMENTS_READ,
  // Attendance (read only)
  PERMISSIONS.ATTENDANCE_READ,
  // Assessments and grades (read only)
  PERMISSIONS.ASSESSMENTS_READ,
  PERMISSIONS.GRADES_READ,
  // Report cards (read only)
  PERMISSIONS.REPORT_CARDS_READ,
  // Timetable (read only)
  PERMISSIONS.TIMETABLE_READ,
  // Finance (read only)
  PERMISSIONS.FEE_STRUCTURES_READ,
  PERMISSIONS.INVOICES_READ,
  PERMISSIONS.PAYMENTS_READ,
  PERMISSIONS.RECEIPTS_READ,
  PERMISSIONS.DISCOUNTS_READ,
  PERMISSIONS.SCHOLARSHIPS_READ,
  PERMISSIONS.FINANCIAL_REPORTS_READ,
  // Communication
  PERMISSIONS.ANNOUNCEMENTS_READ,
  PERMISSIONS.NOTIFICATIONS_READ,
  // Files
  PERMISSIONS.FILES_READ,
  PERMISSIONS.FILES_UPLOAD,
  PERMISSIONS.FILES_UPDATE,
  PERMISSIONS.FILES_DELETE,
  // Audit
  PERMISSIONS.AUDIT_LOGS_READ,
  PERMISSIONS.AUDIT_LOGS_EXPORT,
];

const SCHOOL_ADMIN_PERMS: Permission[] = [
  // System
  PERMISSIONS.SYSTEM_READ,
  PERMISSIONS.SYSTEM_UPDATE,
  PERMISSIONS.SYSTEM_CONFIGURATION,
  // Users
  PERMISSIONS.USERS_READ,
  PERMISSIONS.USERS_CREATE,
  PERMISSIONS.USERS_UPDATE,
  PERMISSIONS.USERS_ARCHIVE,
  PERMISSIONS.USERS_RESET_PASSWORD,
  PERMISSIONS.USERS_ASSIGN_ROLES,
  // Roles and permissions (read + assign)
  PERMISSIONS.ROLES_READ,
  PERMISSIONS.PERMISSIONS_READ,
  PERMISSIONS.PERMISSIONS_ASSIGN,
  PERMISSIONS.SECURITY_READ,
  // Students
  PERMISSIONS.STUDENTS_READ,
  PERMISSIONS.STUDENTS_CREATE,
  PERMISSIONS.STUDENTS_UPDATE,
  PERMISSIONS.STUDENTS_ARCHIVE,
  PERMISSIONS.STUDENTS_RESTORE,
  PERMISSIONS.STUDENTS_VIEW_SENSITIVE,
  // Parents
  PERMISSIONS.PARENTS_READ,
  PERMISSIONS.PARENTS_CREATE,
  PERMISSIONS.PARENTS_UPDATE,
  PERMISSIONS.PARENTS_ARCHIVE,
  PERMISSIONS.PARENTS_RESTORE,
  PERMISSIONS.PARENT_STUDENT_MANAGE,
  // Teachers
  PERMISSIONS.TEACHERS_READ,
  PERMISSIONS.TEACHERS_CREATE,
  PERMISSIONS.TEACHERS_UPDATE,
  PERMISSIONS.TEACHERS_ARCHIVE,
  PERMISSIONS.TEACHERS_RESTORE,
  PERMISSIONS.TEACHER_ASSIGNMENTS_READ,
  PERMISSIONS.TEACHER_ASSIGNMENTS_CREATE,
  PERMISSIONS.TEACHER_ASSIGNMENTS_UPDATE,
  PERMISSIONS.TEACHER_ASSIGNMENTS_DELETE,
  // Academic structure
  PERMISSIONS.ACADEMIC_YEARS_READ,
  PERMISSIONS.ACADEMIC_YEARS_CREATE,
  PERMISSIONS.ACADEMIC_YEARS_UPDATE,
  PERMISSIONS.ACADEMIC_YEARS_CLOSE,
  PERMISSIONS.TERMS_READ,
  PERMISSIONS.TERMS_CREATE,
  PERMISSIONS.TERMS_UPDATE,
  PERMISSIONS.TERMS_CLOSE,
  PERMISSIONS.LEVELS_READ,
  PERMISSIONS.LEVELS_CREATE,
  PERMISSIONS.LEVELS_UPDATE,
  PERMISSIONS.PATHWAYS_READ,
  PERMISSIONS.PATHWAYS_CREATE,
  PERMISSIONS.PATHWAYS_UPDATE,
  PERMISSIONS.TRADES_READ,
  PERMISSIONS.TRADES_CREATE,
  PERMISSIONS.TRADES_UPDATE,
  PERMISSIONS.SUBJECTS_READ,
  PERMISSIONS.SUBJECTS_CREATE,
  PERMISSIONS.SUBJECTS_UPDATE,
  PERMISSIONS.MODULES_READ,
  PERMISSIONS.MODULES_CREATE,
  PERMISSIONS.MODULES_UPDATE,
  PERMISSIONS.CLASSES_READ,
  PERMISSIONS.CLASSES_CREATE,
  PERMISSIONS.CLASSES_UPDATE,
  PERMISSIONS.CLASSES_ARCHIVE,
  // Enrollment
  PERMISSIONS.ENROLLMENTS_READ,
  PERMISSIONS.ENROLLMENTS_CREATE,
  PERMISSIONS.ENROLLMENTS_UPDATE,
  PERMISSIONS.ENROLLMENTS_TRANSFER,
  PERMISSIONS.ENROLLMENTS_WITHDRAW,
  PERMISSIONS.ENROLLMENTS_COMPLETE,
  // Attendance
  PERMISSIONS.ATTENDANCE_READ,
  PERMISSIONS.ATTENDANCE_CREATE,
  PERMISSIONS.ATTENDANCE_UPDATE,
  PERMISSIONS.ATTENDANCE_CORRECT,
  PERMISSIONS.ATTENDANCE_REPORTS,
  // Assessments
  PERMISSIONS.ASSESSMENTS_READ,
  PERMISSIONS.ASSESSMENTS_CREATE,
  PERMISSIONS.ASSESSMENTS_UPDATE,
  PERMISSIONS.ASSESSMENTS_ARCHIVE,
  // Grades
  PERMISSIONS.GRADES_READ,
  PERMISSIONS.GRADES_ENTER,
  PERMISSIONS.GRADES_EDIT,
  PERMISSIONS.GRADES_SUBMIT,
  PERMISSIONS.GRADES_REVIEW,
  PERMISSIONS.GRADES_RETURN,
  PERMISSIONS.GRADES_APPROVE,
  PERMISSIONS.GRADES_REQUEST_CORRECTION,
  PERMISSIONS.GRADES_AUTHORIZE_CORRECTION,
  PERMISSIONS.GRADES_CANCEL_CORRECTION,
  PERMISSIONS.GRADES_LOCK,
  PERMISSIONS.GRADES_REQUEST_POST_LOCK_CORRECTION,
  // Grade scales
  PERMISSIONS.GRADE_SCALES_READ,
  PERMISSIONS.GRADE_SCALES_CREATE,
  PERMISSIONS.GRADE_SCALES_UPDATE,
  PERMISSIONS.GRADE_SCALES_ARCHIVE,
  // Report cards
  PERMISSIONS.REPORT_CARDS_READ,
  PERMISSIONS.REPORT_CARDS_GENERATE,
  PERMISSIONS.REPORT_CARDS_REVIEW,
  PERMISSIONS.REPORT_CARDS_UPDATE,
  PERMISSIONS.REPORT_CARDS_APPROVE,
  PERMISSIONS.REPORT_CARDS_PUBLISH,
  PERMISSIONS.REPORT_CARDS_DOWNLOAD,
  PERMISSIONS.REPORT_CARDS_REGENERATE,
  // Timetable
  PERMISSIONS.TIMETABLE_READ,
  PERMISSIONS.TIMETABLE_CREATE,
  PERMISSIONS.TIMETABLE_UPDATE,
  PERMISSIONS.TIMETABLE_PUBLISH,
  PERMISSIONS.TIMETABLE_ARCHIVE,
  PERMISSIONS.TIMETABLE_CONFLICTS_READ,
  PERMISSIONS.TIMETABLE_CONFLICTS_RESOLVE,
  // Finance
  PERMISSIONS.FEE_STRUCTURES_READ,
  PERMISSIONS.FEE_STRUCTURES_CREATE,
  PERMISSIONS.FEE_STRUCTURES_UPDATE,
  PERMISSIONS.FEE_STRUCTURES_ARCHIVE,
  PERMISSIONS.INVOICES_READ,
  PERMISSIONS.INVOICES_CREATE,
  PERMISSIONS.INVOICES_UPDATE,
  PERMISSIONS.INVOICES_CANCEL,
  PERMISSIONS.PAYMENTS_READ,
  PERMISSIONS.PAYMENTS_CREATE,
  PERMISSIONS.PAYMENTS_UPDATE,
  PERMISSIONS.PAYMENTS_REFUND,
  PERMISSIONS.RECEIPTS_READ,
  PERMISSIONS.RECEIPTS_CREATE,
  PERMISSIONS.RECEIPTS_DOWNLOAD,
  PERMISSIONS.DISCOUNTS_READ,
  PERMISSIONS.DISCOUNTS_CREATE,
  PERMISSIONS.DISCOUNTS_APPROVE,
  PERMISSIONS.DISCOUNTS_CANCEL,
  PERMISSIONS.SCHOLARSHIPS_READ,
  PERMISSIONS.SCHOLARSHIPS_CREATE,
  PERMISSIONS.SCHOLARSHIPS_UPDATE,
  PERMISSIONS.SCHOLARSHIPS_ARCHIVE,
  PERMISSIONS.FINANCIAL_REPORTS_READ,
  PERMISSIONS.FINANCIAL_REPORTS_EXPORT,
  // Communication
  PERMISSIONS.ANNOUNCEMENTS_READ,
  PERMISSIONS.ANNOUNCEMENTS_CREATE,
  PERMISSIONS.ANNOUNCEMENTS_UPDATE,
  PERMISSIONS.ANNOUNCEMENTS_PUBLISH,
  PERMISSIONS.ANNOUNCEMENTS_ARCHIVE,
  PERMISSIONS.NOTIFICATIONS_READ,
  PERMISSIONS.NOTIFICATIONS_MANAGE,
  // Files
  PERMISSIONS.FILES_READ,
  PERMISSIONS.FILES_UPLOAD,
  PERMISSIONS.FILES_UPDATE,
  PERMISSIONS.FILES_DELETE,
  // Audit
  PERMISSIONS.AUDIT_LOGS_READ,
  PERMISSIONS.AUDIT_LOGS_EXPORT,
];

const PRINCIPAL_PERMS: Permission[] = [
  // Users (read only)
  PERMISSIONS.USERS_READ,
  // Students
  PERMISSIONS.STUDENTS_READ,
  PERMISSIONS.STUDENTS_VIEW_SENSITIVE,
  // Parents
  PERMISSIONS.PARENTS_READ,
  // Teachers
  PERMISSIONS.TEACHERS_READ,
  PERMISSIONS.TEACHER_ASSIGNMENTS_READ,
  // Academic structure
  PERMISSIONS.ACADEMIC_YEARS_READ,
  PERMISSIONS.ACADEMIC_YEARS_CLOSE,
  PERMISSIONS.TERMS_READ,
  PERMISSIONS.TERMS_CLOSE,
  PERMISSIONS.LEVELS_READ,
  PERMISSIONS.PATHWAYS_READ,
  PERMISSIONS.TRADES_READ,
  PERMISSIONS.SUBJECTS_READ,
  PERMISSIONS.MODULES_READ,
  PERMISSIONS.CLASSES_READ,
  // Enrollment
  PERMISSIONS.ENROLLMENTS_READ,
  PERMISSIONS.ENROLLMENTS_TRANSFER,
  PERMISSIONS.ENROLLMENTS_COMPLETE,
  // Attendance
  PERMISSIONS.ATTENDANCE_READ,
  PERMISSIONS.ATTENDANCE_UPDATE,
  PERMISSIONS.ATTENDANCE_CORRECT,
  PERMISSIONS.ATTENDANCE_REPORTS,
  // Assessments
  PERMISSIONS.ASSESSMENTS_READ,
  PERMISSIONS.ASSESSMENTS_CREATE,
  PERMISSIONS.ASSESSMENTS_UPDATE,
  // Grades
  PERMISSIONS.GRADES_READ,
  PERMISSIONS.GRADES_ENTER,
  PERMISSIONS.GRADES_EDIT,
  PERMISSIONS.GRADES_SUBMIT,
  PERMISSIONS.GRADES_REVIEW,
  PERMISSIONS.GRADES_RETURN,
  PERMISSIONS.GRADES_APPROVE,
  PERMISSIONS.GRADES_REQUEST_CORRECTION,
  PERMISSIONS.GRADES_AUTHORIZE_CORRECTION,
  PERMISSIONS.GRADES_CANCEL_CORRECTION,
  PERMISSIONS.GRADES_LOCK,
  PERMISSIONS.GRADES_REQUEST_POST_LOCK_CORRECTION,
  // Report cards
  PERMISSIONS.REPORT_CARDS_READ,
  PERMISSIONS.REPORT_CARDS_GENERATE,
  PERMISSIONS.REPORT_CARDS_REVIEW,
  PERMISSIONS.REPORT_CARDS_UPDATE,
  PERMISSIONS.REPORT_CARDS_APPROVE,
  PERMISSIONS.REPORT_CARDS_PUBLISH,
  PERMISSIONS.REPORT_CARDS_DOWNLOAD,
  PERMISSIONS.REPORT_CARDS_REGENERATE,
  // Timetable
  PERMISSIONS.TIMETABLE_READ,
  PERMISSIONS.TIMETABLE_CREATE,
  PERMISSIONS.TIMETABLE_UPDATE,
  PERMISSIONS.TIMETABLE_PUBLISH,
  PERMISSIONS.TIMETABLE_CONFLICTS_READ,
  PERMISSIONS.TIMETABLE_CONFLICTS_RESOLVE,
  // Finance (read + approval actions)
  PERMISSIONS.FEE_STRUCTURES_READ,
  PERMISSIONS.INVOICES_READ,
  PERMISSIONS.PAYMENTS_READ,
  PERMISSIONS.PAYMENTS_REFUND,
  PERMISSIONS.RECEIPTS_READ,
  PERMISSIONS.RECEIPTS_DOWNLOAD,
  PERMISSIONS.DISCOUNTS_READ,
  PERMISSIONS.DISCOUNTS_APPROVE,
  PERMISSIONS.DISCOUNTS_CANCEL,
  PERMISSIONS.SCHOLARSHIPS_READ,
  PERMISSIONS.SCHOLARSHIPS_CREATE,
  PERMISSIONS.SCHOLARSHIPS_UPDATE,
  PERMISSIONS.SCHOLARSHIPS_ARCHIVE,
  PERMISSIONS.FINANCIAL_REPORTS_READ,
  PERMISSIONS.FINANCIAL_REPORTS_EXPORT,
  // Communication
  PERMISSIONS.ANNOUNCEMENTS_READ,
  PERMISSIONS.ANNOUNCEMENTS_CREATE,
  PERMISSIONS.ANNOUNCEMENTS_UPDATE,
  PERMISSIONS.ANNOUNCEMENTS_PUBLISH,
  PERMISSIONS.ANNOUNCEMENTS_ARCHIVE,
  PERMISSIONS.NOTIFICATIONS_READ,
  PERMISSIONS.NOTIFICATIONS_MANAGE,
  // Files
  PERMISSIONS.FILES_READ,
  PERMISSIONS.FILES_UPLOAD,
  PERMISSIONS.FILES_UPDATE,
  PERMISSIONS.FILES_DELETE,
  // Audit
  PERMISSIONS.AUDIT_LOGS_READ,
  PERMISSIONS.AUDIT_LOGS_EXPORT,
];

const TEACHER_PERMS: Permission[] = [
  // Students (scoped)
  PERMISSIONS.STUDENTS_READ,
  // Parents (scoped)
  PERMISSIONS.PARENTS_READ,
  // Teachers (scoped)
  PERMISSIONS.TEACHERS_READ,
    PERMISSIONS.TEACHER_ASSIGNMENTS_READ,
  // Academic structure (scoped)
  PERMISSIONS.ACADEMIC_YEARS_READ,
  PERMISSIONS.TERMS_READ,
  PERMISSIONS.LEVELS_READ,
  PERMISSIONS.PATHWAYS_READ,
  PERMISSIONS.TRADES_READ,
  PERMISSIONS.SUBJECTS_READ,
  PERMISSIONS.MODULES_READ,
  PERMISSIONS.CLASSES_READ,
  // Enrollment (read only, scoped)
  PERMISSIONS.ENROLLMENTS_READ,
  // Attendance
  PERMISSIONS.ATTENDANCE_READ,
  PERMISSIONS.ATTENDANCE_CREATE,
  PERMISSIONS.ATTENDANCE_UPDATE,
  PERMISSIONS.ATTENDANCE_REPORTS,
  // Assessments
  PERMISSIONS.ASSESSMENTS_READ,
  PERMISSIONS.ASSESSMENTS_CREATE,
  PERMISSIONS.ASSESSMENTS_UPDATE,
  // Grades (scoped)
  PERMISSIONS.GRADES_READ,
  PERMISSIONS.GRADES_ENTER,
  PERMISSIONS.GRADES_EDIT,
  PERMISSIONS.GRADES_SUBMIT,
  PERMISSIONS.GRADES_REQUEST_CORRECTION,
  // Report cards (scoped read + download)
  PERMISSIONS.REPORT_CARDS_READ,
  PERMISSIONS.REPORT_CARDS_DOWNLOAD,
  // Timetable (scoped)
  PERMISSIONS.TIMETABLE_READ,
  PERMISSIONS.TIMETABLE_CONFLICTS_READ,
  // Communication
  PERMISSIONS.ANNOUNCEMENTS_READ,
  PERMISSIONS.ANNOUNCEMENTS_CREATE,
  PERMISSIONS.ANNOUNCEMENTS_UPDATE,
  PERMISSIONS.NOTIFICATIONS_READ,
  PERMISSIONS.NOTIFICATIONS_MANAGE,
  // Files (scoped)
  PERMISSIONS.FILES_READ,
  PERMISSIONS.FILES_UPLOAD,
  PERMISSIONS.FILES_UPDATE,
];

const ACCOUNTANT_PERMS: Permission[] = [
  // Academic structure (read only)
  PERMISSIONS.ACADEMIC_YEARS_READ,
  PERMISSIONS.TERMS_READ,
  PERMISSIONS.LEVELS_READ,
  PERMISSIONS.PATHWAYS_READ,
  PERMISSIONS.TRADES_READ,
  // Students (read only, for fee lookup)
  PERMISSIONS.STUDENTS_READ,
  // Enrollment (read only)
  PERMISSIONS.ENROLLMENTS_READ,
  // Finance — full management
  PERMISSIONS.FEE_STRUCTURES_READ,
  PERMISSIONS.FEE_STRUCTURES_CREATE,
  PERMISSIONS.FEE_STRUCTURES_UPDATE,
  PERMISSIONS.FEE_STRUCTURES_ARCHIVE,
  PERMISSIONS.INVOICES_READ,
  PERMISSIONS.INVOICES_CREATE,
  PERMISSIONS.INVOICES_UPDATE,
  PERMISSIONS.INVOICES_CANCEL,
  PERMISSIONS.PAYMENTS_READ,
  PERMISSIONS.PAYMENTS_CREATE,
  PERMISSIONS.PAYMENTS_UPDATE,
  PERMISSIONS.PAYMENTS_REFUND,
  PERMISSIONS.RECEIPTS_READ,
  PERMISSIONS.RECEIPTS_CREATE,
  PERMISSIONS.RECEIPTS_DOWNLOAD,
  PERMISSIONS.DISCOUNTS_READ,
  PERMISSIONS.DISCOUNTS_CREATE,
  PERMISSIONS.DISCOUNTS_APPROVE,
  PERMISSIONS.DISCOUNTS_CANCEL,
  PERMISSIONS.SCHOLARSHIPS_READ,
  PERMISSIONS.SCHOLARSHIPS_CREATE,
  PERMISSIONS.SCHOLARSHIPS_UPDATE,
  PERMISSIONS.SCHOLARSHIPS_ARCHIVE,
  PERMISSIONS.FINANCIAL_REPORTS_READ,
  PERMISSIONS.FINANCIAL_REPORTS_EXPORT,
  // Communication
  PERMISSIONS.ANNOUNCEMENTS_READ,
  PERMISSIONS.ANNOUNCEMENTS_CREATE,
  PERMISSIONS.ANNOUNCEMENTS_UPDATE,
  PERMISSIONS.NOTIFICATIONS_READ,
  PERMISSIONS.NOTIFICATIONS_MANAGE,
  // Files
  PERMISSIONS.FILES_READ,
  PERMISSIONS.FILES_UPLOAD,
  PERMISSIONS.FILES_UPDATE,
  PERMISSIONS.FILES_DELETE,
  // Audit (scoped)
  PERMISSIONS.AUDIT_LOGS_READ,
];

const REGISTRAR_PERMS: Permission[] = [
  // Users (read only)
  PERMISSIONS.USERS_READ,
  // Students — full operational management
  PERMISSIONS.STUDENTS_READ,
  PERMISSIONS.STUDENTS_CREATE,
  PERMISSIONS.STUDENTS_UPDATE,
  PERMISSIONS.STUDENTS_ARCHIVE,
  PERMISSIONS.STUDENTS_RESTORE,
  PERMISSIONS.STUDENTS_VIEW_SENSITIVE,
  // Parents
  PERMISSIONS.PARENTS_READ,
  PERMISSIONS.PARENTS_CREATE,
  PERMISSIONS.PARENTS_UPDATE,
  PERMISSIONS.PARENTS_ARCHIVE,
  PERMISSIONS.PARENT_STUDENT_MANAGE,
  // Teachers (read only)
  PERMISSIONS.TEACHERS_READ,
  PERMISSIONS.TEACHER_ASSIGNMENTS_READ,
  // Academic structure
  PERMISSIONS.ACADEMIC_YEARS_READ,
  PERMISSIONS.TERMS_READ,
  PERMISSIONS.LEVELS_READ,
  PERMISSIONS.PATHWAYS_READ,
  PERMISSIONS.TRADES_READ,
  PERMISSIONS.SUBJECTS_READ,
  PERMISSIONS.MODULES_READ,
  PERMISSIONS.CLASSES_READ,
  // Enrollment — full management
  PERMISSIONS.ENROLLMENTS_READ,
  PERMISSIONS.ENROLLMENTS_CREATE,
  PERMISSIONS.ENROLLMENTS_UPDATE,
  PERMISSIONS.ENROLLMENTS_TRANSFER,
  PERMISSIONS.ENROLLMENTS_WITHDRAW,
  PERMISSIONS.ENROLLMENTS_COMPLETE,
  // Attendance (read + correct)
  PERMISSIONS.ATTENDANCE_READ,
  PERMISSIONS.ATTENDANCE_UPDATE,
  PERMISSIONS.ATTENDANCE_CORRECT,
  PERMISSIONS.ATTENDANCE_REPORTS,
  // Assessments (read only)
  PERMISSIONS.ASSESSMENTS_READ,
  // Grades (read only)
  PERMISSIONS.GRADES_READ,
  // Report cards (generate + read, no approve)
  PERMISSIONS.REPORT_CARDS_READ,
  PERMISSIONS.REPORT_CARDS_GENERATE,
  PERMISSIONS.REPORT_CARDS_REVIEW,
  PERMISSIONS.REPORT_CARDS_UPDATE,
  PERMISSIONS.REPORT_CARDS_DOWNLOAD,
  PERMISSIONS.REPORT_CARDS_REGENERATE,
  // Timetable (read + create)
  PERMISSIONS.TIMETABLE_READ,
  PERMISSIONS.TIMETABLE_CREATE,
  PERMISSIONS.TIMETABLE_UPDATE,
  PERMISSIONS.TIMETABLE_CONFLICTS_READ,
  // Finance (read only)
  PERMISSIONS.FEE_STRUCTURES_READ,
  PERMISSIONS.INVOICES_READ,
  PERMISSIONS.PAYMENTS_READ,
  PERMISSIONS.RECEIPTS_READ,
  PERMISSIONS.RECEIPTS_DOWNLOAD,
  PERMISSIONS.DISCOUNTS_READ,
  PERMISSIONS.SCHOLARSHIPS_READ,
  // Communication
  PERMISSIONS.ANNOUNCEMENTS_READ,
  PERMISSIONS.ANNOUNCEMENTS_CREATE,
  PERMISSIONS.ANNOUNCEMENTS_UPDATE,
  PERMISSIONS.NOTIFICATIONS_READ,
  PERMISSIONS.NOTIFICATIONS_MANAGE,
  // Files
  PERMISSIONS.FILES_READ,
  PERMISSIONS.FILES_UPLOAD,
  PERMISSIONS.FILES_UPDATE,
  PERMISSIONS.FILES_DELETE,
  // Audit
  PERMISSIONS.AUDIT_LOGS_READ,
];

const PARENT_PERMS: Permission[] = [
  // Academic structure (read only, scoped)
  PERMISSIONS.ACADEMIC_YEARS_READ,
  PERMISSIONS.TERMS_READ,
  PERMISSIONS.LEVELS_READ,
  PERMISSIONS.PATHWAYS_READ,
  PERMISSIONS.TRADES_READ,
  PERMISSIONS.SUBJECTS_READ,
  PERMISSIONS.MODULES_READ,
  PERMISSIONS.CLASSES_READ,
  // Students (own children, scoped)
  PERMISSIONS.STUDENTS_READ,
  PERMISSIONS.PARENTS_READ,
  // Enrollment (own children)
  PERMISSIONS.ENROLLMENTS_READ,
  // Attendance (own children)
  PERMISSIONS.ATTENDANCE_READ,
  PERMISSIONS.ATTENDANCE_REPORTS,
  // Grades (own children)
  PERMISSIONS.GRADES_READ,
  // Report cards (own children)
  PERMISSIONS.REPORT_CARDS_READ,
  PERMISSIONS.REPORT_CARDS_DOWNLOAD,
  // Timetable (own children)
  PERMISSIONS.TIMETABLE_READ,
  // Finance (own children)
  PERMISSIONS.FEE_STRUCTURES_READ,
  PERMISSIONS.INVOICES_READ,
  PERMISSIONS.PAYMENTS_READ,
  PERMISSIONS.RECEIPTS_READ,
  PERMISSIONS.RECEIPTS_DOWNLOAD,
  PERMISSIONS.DISCOUNTS_READ,
  PERMISSIONS.SCHOLARSHIPS_READ,
  // Communication
  PERMISSIONS.ANNOUNCEMENTS_READ,
  PERMISSIONS.NOTIFICATIONS_READ,
  // Files (own children's documents)
  PERMISSIONS.FILES_READ,
  PERMISSIONS.FILES_UPLOAD,
];

const STUDENT_PERMS: Permission[] = [
  // Academic structure (read only, scoped)
  PERMISSIONS.ACADEMIC_YEARS_READ,
  PERMISSIONS.TERMS_READ,
  PERMISSIONS.LEVELS_READ,
  PERMISSIONS.PATHWAYS_READ,
  PERMISSIONS.TRADES_READ,
  PERMISSIONS.SUBJECTS_READ,
  PERMISSIONS.MODULES_READ,
  PERMISSIONS.CLASSES_READ,
  // Self
  PERMISSIONS.STUDENTS_READ,
  // Enrollment (self)
  PERMISSIONS.ENROLLMENTS_READ,
  // Attendance (self)
  PERMISSIONS.ATTENDANCE_READ,
  PERMISSIONS.ATTENDANCE_REPORTS,
  // Grades (self)
  PERMISSIONS.GRADES_READ,
  // Report cards (read only — no download in V1)
  PERMISSIONS.REPORT_CARDS_READ,
  // Timetable
  PERMISSIONS.TIMETABLE_READ,
  // Finance (self)
  PERMISSIONS.FEE_STRUCTURES_READ,
  PERMISSIONS.INVOICES_READ,
  PERMISSIONS.PAYMENTS_READ,
  PERMISSIONS.RECEIPTS_READ,
  PERMISSIONS.DISCOUNTS_READ,
  PERMISSIONS.SCHOLARSHIPS_READ,
  // Communication
  PERMISSIONS.ANNOUNCEMENTS_READ,
  PERMISSIONS.NOTIFICATIONS_READ,
  // Files (own)
  PERMISSIONS.FILES_READ,
];

// ------------------------------------------------------------
// Complete role → permission mapping
// ------------------------------------------------------------

const ROLE_PERMISSIONS: Record<RoleKey, Permission[]> = {
  [ROLES.SYSTEM_ADMIN]: SYSTEM_ADMIN_PERMS,
  [ROLES.SCHOOL_ADMIN]: SCHOOL_ADMIN_PERMS,
  [ROLES.PRINCIPAL]: PRINCIPAL_PERMS,
  [ROLES.TEACHER]: TEACHER_PERMS,
  [ROLES.ACCOUNTANT]: ACCOUNTANT_PERMS,
  [ROLES.REGISTRAR]: REGISTRAR_PERMS,
  [ROLES.PARENT]: PARENT_PERMS,
  [ROLES.STUDENT]: STUDENT_PERMS,
};

// ------------------------------------------------------------
// Seed function
// ------------------------------------------------------------

export async function seedRbac(prisma: PrismaClient): Promise<void> {
  console.log("🌱 Seeding RBAC (roles, permissions, role-permissions)...");

  // 1. Upsert roles
  let roleCount = 0;
  for (const roleKey of Object.values(ROLES)) {
    const meta = ROLE_METADATA[roleKey];
    await prisma.role.upsert({
      where: { key: roleKey },
      update: {
        name: meta.name,
        description: meta.description,
        isSystem: meta.isSystem,
      },
      create: {
        key: roleKey,
        name: meta.name,
        description: meta.description,
        isSystem: meta.isSystem,
      },
    });
    roleCount++;
  }
  console.log(`  ✓ Roles upserted: ${roleCount}`);

  // 2. Upsert permissions
  let permCount = 0;
  for (const perm of PERMISSION_SEEDS) {
    await prisma.permission.upsert({
      where: { key: perm.key },
      update: {
        category: perm.category,
        description: perm.description,
      },
      create: {
        key: perm.key,
        category: perm.category,
        description: perm.description,
      },
    });
    permCount++;
  }
  console.log(`  ✓ Permissions upserted: ${permCount}`);

  // 3. Load all roles and permissions into maps for fast lookup
  const allRoles = await prisma.role.findMany();
  const allPerms = await prisma.permission.findMany();

  const roleByKey = new Map(allRoles.map((r) => [r.key, r]));
  const permByKey = new Map(allPerms.map((p) => [p.key, p]));

  // 4. Upsert role-permission links
  let linkCount = 0;

  for (const [roleKey, permKeys] of Object.entries(ROLE_PERMISSIONS) as [
    RoleKey,
    Permission[],
  ][]) {
    const role = roleByKey.get(roleKey);
    if (!role) {
      console.warn(`  ⚠ Role not found: ${roleKey} — skipping`);
      continue;
    }

    for (const permKey of permKeys) {
      const perm = permByKey.get(permKey);
      if (!perm) {
        console.warn(`  ⚠ Permission not found: ${permKey} — skipping`);
        continue;
      }

      await prisma.rolePermission.upsert({
        where: {
          roleId_permissionId: {
            roleId: role.id,
            permissionId: perm.id,
          },
        },
        update: {},
        create: {
          roleId: role.id,
          permissionId: perm.id,
        },
      });
      linkCount++;
    }
  }
  console.log(`  ✓ Role-permission links upserted: ${linkCount}`);

  console.log("✅ RBAC seeding complete.\n");
}

// ------------------------------------------------------------
// Exported summary for verification
// ------------------------------------------------------------

export function getRbacSummary() {
  const summary = Object.entries(ROLE_PERMISSIONS).map(
    ([roleKey, perms]) => ({
      roleKey,
      permissionCount: perms.length,
    }),
  );

  const total = summary.reduce((acc, r) => acc + r.permissionCount, 0);

  return {
    roleCount: Object.keys(ROLES).length,
    permissionCount: PERMISSION_SEEDS.length,
    totalRolePermissionLinks: total,
    byRole: summary,
  };
}